/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EssaysIndexRouteImport } from './routes/essays.index'
import { Route as EssaysSlugRouteImport } from './routes/essays.$slug'

const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaysIndexRoute = EssaysIndexRouteImport.update({
  id: '/essays/',
  path: '/essays/',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaysSlugRoute = EssaysSlugRouteImport.update({
  id: '/essays/$slug',
  path: '/essays/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/playbook': typeof PlaybookRoute
  '/essays/$slug': typeof EssaysSlugRoute
  '/essays/': typeof EssaysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/playbook': typeof PlaybookRoute
  '/essays/$slug': typeof EssaysSlugRoute
  '/essays': typeof EssaysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/playbook': typeof PlaybookRoute
  '/essays/$slug': typeof EssaysSlugRoute
  '/essays/': typeof EssaysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/playbook' | '/essays/$slug' | '/essays/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/playbook' | '/essays/$slug' | '/essays'
  id: '__root__' | '/' | '/about' | '/playbook' | '/essays/$slug' | '/essays/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PlaybookRoute: typeof PlaybookRoute
  EssaysSlugRoute: typeof EssaysSlugRoute
  EssaysIndexRoute: typeof EssaysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essays/': {
      id: '/essays/'
      path: '/essays'
      fullPath: '/essays/'
      preLoaderRoute: typeof EssaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essays/$slug': {
      id: '/essays/$slug'
      path: '/essays/$slug'
      fullPath: '/essays/$slug'
      preLoaderRoute: typeof EssaysSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PlaybookRoute: PlaybookRoute,
  EssaysSlugRoute: EssaysSlugRoute,
  EssaysIndexRoute: EssaysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
